### ISSUE TITLE
No issues have been selected

### ISSUE THREAD

**Issue by farghc** [buschmais/redmics#31]
Hello,
thank you for your very useful plugin. Unfortunately for me it is not working anymore.

Redmine version                4.1.1.stable
Ruby version                   2.5.5

I get the following log entry when synchronizing the calendar from Thunderbird.

Started GET "/icalendar/test-project/all/issues.ics?key=<my_api_key>" for <my_ip>
Processing by ICalendarController#index as ICS
  Parameters: {"key"=>"<my_api_key>", "project_id"=>"test_project", "assignment"=>"all"}
  Current user: test_user (id=5)
No issues have been selected. undefined method `delete' for nil:NilClass
  Rendering text template
  Rendered text template (0.0ms)
Sent data  (0.4ms)
Completed 200 OK in 22ms (Views: 0.4ms | ActiveRecord: 11.3ms)

Issues should be present with due date set.

Thank you in advance for your support.
Best wishes

**Comment by fs5** [comment]
The plugin does nowhere call a method "delete" when building the ICS response. The issue might stem from another plugin.

Please provide a stacktrace when your reopen the issue.

**Comment by Jacq** [comment]
In my case this error raises from the redmineup tags plugin, you can check the source by adding a "raise e" of the exception after these lines:
- https://github.com/buschmais/redmics/blob/001c74f9313f7f6a9a8897a8d33e398bd2ae8ae4/lib/redmics/export.rb#L76
- https://github.com/buschmais/redmics/blob/001c74f9313f7f6a9a8897a8d33e398bd2ae8ae4/lib/redmics/export.rb#L132

I am not use to ruby code, nor redmine code but it seems that the culprit is the redmics plugin, settings filters to nil in this line causes further plugins to fail when using the filters list: https://github.com/buschmais/redmics/blob/001c74f9313f7f6a9a8897a8d33e398bd2ae8ae4/lib/redmics/export.rb#L108C9-L108C23
